#springdoc:
#  api-docs:
#    path: /openapi
server:
  port: 3000

spring:
  spring:
    datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:39092
    group-id: activity-consumer-group
    topic:
      rollback:
        name: awards-by-organization-rollback
      activity:
        name: awards-by-organization-activity
  activity:
    delay: 0
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#  jpa:
#    show-sql: true
#    properties:
#      ## Hibernate Properties
#      # The SQL dialect makes Hibernate generate better SQL for the chosen database
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    # Hibernate ddl auto (create, create-drop, validate, update)
#    hibernate:
#      ddl-auto: update
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/templates/
      cache:
        period: 0
